version: '3.8'

services: 
  nodejs: 
    container_name: node-api
    build: 
      context: .
      dockerfile: Dockerfile
    # command: npm run dev
    volumes: 
      - '.:/usr/app'
      - /usr/app/node_modules
    restart: always
    ports: 
      - '9000:4000'
    depends_on:
      - mongo
    env_file: 
      .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    external_links:
        - mongo
    
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    # volumes:
    #     - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    # volumes:
      # - ./mongodb/mongod.conf:/etc/mongod.conf
      # - ./mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      # - ./mongodb/data/db/:/data/db/
      # - ./mongodb/data/log/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #   MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    # command: ["-f", "/etc/mongod.conf"]
    env_file: 
      - .env
    ports:
        - 27017:27017
    # command:
    #   [--auth]
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}


